//Effects
CoC.data.effects = new Backbone.Collection([

  { uid: "attack", name:"Attack", image:"images/effects/attack.jpg", base:5 },
  { uid: "critrate", name:"Critical Rate", image:"images/effects/critical.jpg", base:5 },
  { uid: "critdamage", name:"Critical Damage", image:"images/effects/critical.jpg", base:15 },
  { uid: "stun", name:"Stun", image:"images/effects/stun.jpg", base:15 },
  { uid: "powergain", name:"Power Gain", image:"images/effects/mana.jpg", base:3 },
  { uid: "powersteal", name:"Power Steal", image:"images/effects/mana_steal.jpg", base:3 },
  { uid: "perfectblock", name:"Perfect Block", image:"images/effects/block.jpg", base:3 },
  { uid: "block", name:"Block Proficiency", image:"images/effects/block.jpg", base:10 },
  { uid: "armor", name:"Armor", image:"images/effects/armor.jpg", base:4 },
  { uid: "health", name:"Health", image:"images/effects/health.jpg", base:4 },
  { uid: "healthsteal", name:"Health Steal", image:"images/effects/health_steal.jpg", base:4 }

], {
  model: CoC.model.Effect
});

//Champion Types
CoC.data.types = new Backbone.Collection([

  { uid:"cosmic", name:"Cosmic", image:"images/icons/cosmic.png" },
  { uid:"tech", name:"Tech", image:"images/icons/tech.png" },
  { uid:"mutant", name:"Mutant", image:"images/icons/mutant.png" },
  { uid:"skill", name:"Skill", image:"images/icons/skill.png" },
  { uid:"science", name:"Science", image:"images/icons/science.png" },
  { uid:"mystic", name:"Mystic", image:"images/icons/mystic.png" }
  
], {
  model: CoC.model.Type
});

//Champion Ranks and Levels
CoC.data.championLevels={
  1:[ 10, 20 ],
  2:[ 10, 20, 30 ],
  3:[ 10, 20, 30, 40 ],
  4:[ 10, 20, 30, 40, 50 ]
}

//Champions
CoC.data.champions = new Backbone.Collection([
  { uid:"blackbolt", name:"Black Bolt", type:"cosmic", stars: 2 },
  { uid:"blackbolt", name:"Black Bolt", type:"cosmic", stars: 3 },
  { uid:"captainmarvel", name:"Captain Marvel", type:"cosmic", stars: 3 },
  { uid:"captainmarvel", name:"Captain Marvel", type:"cosmic", stars: 4 },
  { uid:"drax", name:"Drax", type:"cosmic", stars: 2 },
  { uid:"drax", name:"Drax", type:"cosmic", stars: 3 },
  { uid:"drax", name:"Drax", type:"cosmic", stars: 4 },
  { uid:"gamora", name:"Gamora", type:"cosmic", stars: 1 },
  { uid:"gamora", name:"Gamora", type:"cosmic", stars: 2 },
  { uid:"gamora", name:"Gamora", type:"cosmic", stars: 3 },
  { uid:"gamora", name:"Gamora", type:"cosmic", stars: 4 },
  { uid:"msmarvel", name:"Ms. Marvel", type:"cosmic", stars: 3 },
  { uid:"msmarvel", name:"Ms. Marvel", type:"cosmic", stars: 4 },
  { uid:"ronan", name:"Ronan", type:"cosmic", stars: 2 },
  { uid:"ronan", name:"Ronan", type:"cosmic", stars: 3 },
  { uid:"ronan", name:"Ronan", type:"cosmic", stars: 4 },
  { uid:"superiorironman", name:"Superior Iron Man", type:"cosmic", stars: 2 },
  { uid:"superiorironman", name:"Superior Iron Man", type:"cosmic", stars: 3 },
  { uid:"superiorironman", name:"Superior Iron Man", type:"cosmic", stars: 4 },
  { uid:"thor", name:"Thor", type:"cosmic", stars: 2 },
  { uid:"thor", name:"Thor", type:"cosmic", stars: 3 },
  { uid:"thor", name:"Thor", type:"cosmic", stars: 4 },
  { uid:"ironman", name:"Iron Man", type:"tech", stars: 1 },
  { uid:"ironman", name:"Iron Man", type:"tech", stars: 2 },
  { uid:"ironman", name:"Iron Man", type:"tech", stars: 3 },
  { uid:"ironman", name:"Iron Man", type:"tech", stars: 4 },
  { uid:"hulkbuster", name:"Hulkbuster", type:"tech", stars: 2 },
  { uid:"hulkbuster", name:"Hulkbuster", type:"tech", stars: 3 },
  { uid:"hulkbuster", name:"Hulkbuster", type:"tech", stars: 4 },
  { uid:"rocket", name:"Rocket Raccoon", type:"tech", stars: 3 },
  { uid:"rocket", name:"Rocket Raccoon", type:"tech", stars: 4 },
  { uid:"starlord", name:"Star-Lord", type:"tech", stars: 2 },
  { uid:"starlord", name:"Star-Lord", type:"tech", stars: 3 },
  { uid:"starlord", name:"Star-Lord", type:"tech", stars: 4 },
  { uid:"vision", name:"Vision", type:"tech", stars: 1 },
  { uid:"vision", name:"Vision", type:"tech", stars: 2 },
  { uid:"vision", name:"Vision", type:"tech", stars: 3 },
  { uid:"vision", name:"Vision", type:"tech", stars: 4 },
  { uid:"thevision", name:"The Vision", type:"tech", stars: 2 },
  { uid:"thevision", name:"The Vision", type:"tech", stars: 3 },
  { uid:"thevision", name:"The Vision", type:"tech", stars: 4 },
  { uid:"ultron", name:"Ultron", type:"tech", stars: 3 },
  { uid:"ultron", name:"Ultron", type:"tech", stars: 4 },
  { uid:"colossus", name:"Colossus", type:"mutant", stars: 1 },
  { uid:"colossus", name:"Colossus", type:"mutant", stars: 2 },
  { uid:"colossus", name:"Colossus", type:"mutant", stars: 3 },
  { uid:"colossus", name:"Colossus", type:"mutant", stars: 4 },
  { uid:"cyclops", name:"Cyclops", type:"mutant", stars: 2 },
  { uid:"cyclops", name:"Cyclops", type:"mutant", stars: 3 },
  { uid:"cyclops", name:"Cyclops", type:"mutant", stars: 4 },
  { uid:"deadpool", name:"Deadpool", type:"mutant", stars: 2 },
  { uid:"deadpool", name:"Deadpool", type:"mutant", stars: 3 },
  { uid:"deadpool", name:"Deadpool", type:"mutant", stars: 4 },
  { uid:"magneto", name:"Magneto", type:"mutant", stars: 3 },
  { uid:"magneto", name:"Magneto", type:"mutant", stars: 4 },
  { uid:"storm", name:"Storm", type:"mutant", stars: 2 },
  { uid:"storm", name:"Storm", type:"mutant", stars: 3 },
  { uid:"storm", name:"Storm", type:"mutant", stars: 4 },
  { uid:"wolverine", name:"Wolverine", type:"mutant", stars: 1 },
  { uid:"wolverine", name:"Wolverine", type:"mutant", stars: 2 },
  { uid:"wolverine", name:"Wolverine", type:"mutant", stars: 3 },
  { uid:"wolverine", name:"Wolverine", type:"mutant", stars: 4 },
  { uid:"blackpanther", name:"Black Panther", type:"skill", stars: 1 },
  { uid:"blackpanther", name:"Black Panther", type:"skill", stars: 2 },
  { uid:"blackpanther", name:"Black Panther", type:"skill", stars: 3 },
  { uid:"blackpanther", name:"Black Panther", type:"skill", stars: 4 },
  { uid:"blackwidow", name:"Black Widow", type:"skill", stars: 2 },
  { uid:"blackwidow", name:"Black Widow", type:"skill", stars: 3 },
  { uid:"blackwidow", name:"Black Widow", type:"skill", stars: 4 },
  { uid:"daredevil", name:"Daredevil", type:"skill", stars: 3 },
  { uid:"daredevil", name:"Daredevil", type:"skill", stars: 4 },
  { uid:"hawkeye", name:"Hawkeye", type:"skill", stars: 1 },
  { uid:"hawkeye", name:"Hawkeye", type:"skill", stars: 2 },
  { uid:"hawkeye", name:"Hawkeye", type:"skill", stars: 3 },
  { uid:"hawkeye", name:"Hawkeye", type:"skill", stars: 4 },
  { uid:"punisher", name:"Punisher", type:"skill", stars: 2 },
  { uid:"punisher", name:"Punisher", type:"skill", stars: 3 },
  { uid:"punisher", name:"Punisher", type:"skill", stars: 4 },
  { uid:"wintersoldier", name:"Winter Soldier", type:"skill", stars: 2 },
  { uid:"wintersoldier", name:"Winter Soldier", type:"skill", stars: 3 },
  { uid:"wintersoldier", name:"Winter Soldier", type:"skill", stars: 4 },
  { uid:"abomination", name:"Abomination", type:"science", stars: 2 },
  { uid:"abomination", name:"Abomination", type:"science", stars: 3 },
  { uid:"abomination", name:"Abomination", type:"science", stars: 4 },
  { uid:"captainamerica", name:"Captain America", type:"science", stars: 2 },
  { uid:"captainamerica", name:"Captain America", type:"science", stars: 3 },
  { uid:"captainamerica", name:"Captain America", type:"science", stars: 4 },
  { uid:"electro", name:"Electro", type:"science", stars: 3 },
  { uid:"electro", name:"Electro", type:"science", stars: 4 },
  { uid:"hulk", name:"Hulk", type:"science", stars: 1 },
  { uid:"hulk", name:"Hulk", type:"science", stars: 2 },
  { uid:"hulk", name:"Hulk", type:"science", stars: 3 },
  { uid:"hulk", name:"Hulk", type:"science", stars: 4 },
  { uid:"rhino", name:"Rhino", type:"science", stars: 2 },
  { uid:"rhino", name:"Rhino", type:"science", stars: 3 },
  { uid:"rhino", name:"Rhino", type:"science", stars: 4 },
  { uid:"spiderman", name:"Spider-Man", type:"science", stars: 1 },
  { uid:"spiderman", name:"Spider-Man", type:"science", stars: 2 },
  { uid:"spiderman", name:"Spider-Man", type:"science", stars: 3 },
  { uid:"spiderman", name:"Spider-Man", type:"science", stars: 4 },
  { uid:"drstrange", name:"Dr. Strange", type:"mystic", stars: 3 },
  { uid:"drstrange", name:"Dr. Strange", type:"mystic", stars: 4 },
  { uid:"ironfist", name:"Iron Fist", type:"mystic", stars: 2 },
  { uid:"ironfist", name:"Iron Fist", type:"mystic", stars: 3 },
  { uid:"juggernaut", name:"Juggernaut", type:"mystic", stars: 1 },
  { uid:"juggernaut", name:"Juggernaut", type:"mystic", stars: 2 },
  { uid:"juggernaut", name:"Juggernaut", type:"mystic", stars: 3 },
  { uid:"juggernaut", name:"Juggernaut", type:"mystic", stars: 4 },
  { uid:"magik", name:"Magik", type:"mystic", stars: 2 },
  { uid:"magik", name:"Magik", type:"mystic", stars: 3 },
  { uid:"magik", name:"Magik", type:"mystic", stars: 4 },
  { uid:"scarletwitch", name:"Scarlet Witch", type:"mystic", stars: 1 },
  { uid:"scarletwitch", name:"Scarlet Witch", type:"mystic", stars: 2 },
  { uid:"scarletwitch", name:"Scarlet Witch", type:"mystic", stars: 3 },
  { uid:"unstoppablecolossus", name:"Unstoppable Colossus", type:"mystic", stars: 2 },
  { uid:"unstoppablecolossus", name:"Unstoppable Colossus", type:"mystic", stars: 3 },
  { uid:"unstoppablecolossus", name:"Unstoppable Colossus", type:"mystic", stars: 4 }
  
], {
  model: CoC.model.Champion
});

//Synergies
CoC.data.synergies = new Backbone.Collection([

  { fromId:"blackbolt", fromStars: 2, toId: "cyclops", effectId:"block", effectAmount:10 },
  { fromId:"blackbolt", fromStars: 3, toId: "cyclops", effectId:"block", effectAmount:15 },
  { fromId:"blackbolt", fromStars: 3, toId: "spiderman", effectId:"armor", effectAmount:5 },
  { fromId:"blackbolt", fromStars: 3, toId: "ronan", effectId:"attack", effectAmount:4 },
  { fromId:"blackbolt", fromStars: 3, toId: "hulk", effectId:"critdamage", effectAmount:20 },

  { fromId:"captainmarvel", fromStars: 3, toId: "captainamerica", effectId:"armor", effectAmount:5 },
  { fromId:"captainmarvel", fromStars: 3, toId: "gamora", effectId:"armor", effectAmount:5 },
  { fromId:"captainmarvel", fromStars: 3, toId: "ironman", effectId:"armor", effectAmount:5 },
  { fromId:"captainmarvel", fromStars: 4, toId: "captainamerica", effectId:"armor", effectAmount:6 },
  { fromId:"captainmarvel", fromStars: 4, toId: "gamora", effectId:"armor", effectAmount:6 },
  { fromId:"captainmarvel", fromStars: 4, toId: "ironman", effectId:"armor", effectAmount:6 },
  { fromId:"captainmarvel", fromStars: 4, toId: "wolverine", effectId:"powergain", effectAmount:5 },

  { fromId:"drax", fromStars:2, toId:"starlord", effectId:"perfectblock", effectAmount:3 },
  { fromId:"drax", fromStars:2, toId:"gamora", effectId:"critdamage", effectAmount:15 },
  { fromId:"drax", fromStars:3, toId:"starlord", effectId:"perfectblock", effectAmount:4 },
  { fromId:"drax", fromStars:3, toId:"gamora", effectId:"critdamage", effectAmount:20 },
  { fromId:"drax", fromStars:4, toId:"starlord", effectId:"perfectblock", effectAmount:5 },
  { fromId:"drax", fromStars:4, toId:"gamora", effectId:"critdamage", effectAmount:25 },

  { fromId:"gamora", fromStars:2, toId:"starlord", effectId:"armor", effectAmount:4 },
  { fromId:"gamora", fromStars:3, toId:"starlord", effectId:"armor", effectAmount:5 },
  { fromId:"gamora", fromStars:3, toId:"drax", effectId:"critdamage", effectAmount:20 },
  { fromId:"gamora", fromStars:4, toId:"starlord", effectId:"armor", effectAmount:6 },
  { fromId:"gamora", fromStars:4, toId:"drax", effectId:"critdamage", effectAmount:25 },

  { fromId:"msmarvel", fromStars:3, toId:"captainamerica", effectId:"armor", effectAmount:5 },
  { fromId:"msmarvel", fromStars:3, toId:"ironman", effectId:"perfectblock", effectAmount:4 },
  { fromId:"msmarvel", fromStars:3, toId:"thor", effectId:"perfectblock", effectAmount:4 },
  { fromId:"msmarvel", fromStars:3, toId:"hulk", effectId:"perfectblock", effectAmount:4 },
  { fromId:"msmarvel", fromStars:4, toId:"captainamerica", effectId:"armor", effectAmount:6 },
  { fromId:"msmarvel", fromStars:4, toId:"ironman", effectId:"perfectblock", effectAmount:5 },
  { fromId:"msmarvel", fromStars:4, toId:"thor", effectId:"perfectblock", effectAmount:5 },
  { fromId:"msmarvel", fromStars:4, toId:"hulk", effectId:"perfectblock", effectAmount:5 },

  { fromId:"ronan", fromStars:2, toId:"blackbolt", effectId:"critdamage", effectAmount:15 },
  { fromId:"ronan", fromStars:3, toId:"blackbolt", effectId:"critdamage", effectAmount:20 },
  { fromId:"ronan", fromStars:3, toId:"ironman", effectId:"critrate", effectAmount:6 },
  { fromId:"ronan", fromStars:3, toId:"gamora", effectId:"critdamage", effectAmount:20 },
  { fromId:"ronan", fromStars:4, toId:"blackbolt", effectId:"critdamage", effectAmount:25 },
  { fromId:"ronan", fromStars:4, toId:"ironman", effectId:"critrate", effectAmount:7 },
  { fromId:"ronan", fromStars:4, toId:"gamora", effectId:"critdamage", effectAmount:25 },

  { fromId:"superiorironman", fromStars:2, toId:"captainamerica", effectId:"critrate", effectAmount:5 },
  { fromId:"superiorironman", fromStars:2, toId:"daredevil", effectId:"critdamage", effectAmount:15 },
  { fromId:"superiorironman", fromStars:2, toId:"thor", effectId:"perfectblock", effectAmount:3 },
  { fromId:"superiorironman", fromStars:3, toId:"captainamerica", effectId:"critrate", effectAmount:6 },
  { fromId:"superiorironman", fromStars:3, toId:"daredevil", effectId:"critdamage", effectAmount:20 },
  { fromId:"superiorironman", fromStars:3, toId:"thor", effectId:"perfectblock", effectAmount:4 },
  { fromId:"superiorironman", fromStars:4, toId:"captainamerica", effectId:"critrate", effectAmount:7 },
  { fromId:"superiorironman", fromStars:4, toId:"daredevil", effectId:"critdamage", effectAmount:25 },
  { fromId:"superiorironman", fromStars:4, toId:"thor", effectId:"perfectblock", effectAmount:4 },

  { fromId:"thor", fromStars:2, toId:"drstrange", effectId:"armor", effectAmount:4 },
  { fromId:"thor", fromStars:2, toId:"ironman", effectId:"armor", effectAmount:4 },
  { fromId:"thor", fromStars:3, toId:"drstrange", effectId:"armor", effectAmount:5 },
  { fromId:"thor", fromStars:3, toId:"ironman", effectId:"armor", effectAmount:5 },
  { fromId:"thor", fromStars:3, toId:"juggernaut", effectId:"armor", effectAmount:6 },
  { fromId:"thor", fromStars:4, toId:"drstrange", effectId:"armor", effectAmount:6 },
  { fromId:"thor", fromStars:4, toId:"ironman", effectId:"armor", effectAmount:6 },
  { fromId:"thor", fromStars:4, toId:"juggernaut", effectId:"armor", effectAmount:7 },

  { fromId:"ironman", fromStars:2, toId:"thor", effectId:"perfectblock", effectAmount:3 },
  { fromId:"ironman", fromStars:3, toId:"captainamerica", effectId:"armor", effectAmount:5 },
  { fromId:"ironman", fromStars:3, toId:"thor", effectId:"perfectblock", effectAmount:4 },
  { fromId:"ironman", fromStars:4, toId:"captainamerica", effectId:"armor", effectAmount:6 },
  { fromId:"ironman", fromStars:4, toId:"thor", effectId:"perfectblock", effectAmount:5 },

  { fromId:"hulkbuster", fromStars:2, toId:"hulk", effectId:"critdamage", effectAmount:15 },
  { fromId:"hulkbuster", fromStars:3, toId:"hulk", effectId:"critdamage", effectAmount:20 },
  { fromId:"hulkbuster", fromStars:3, toId:"ironman", effectId:"perfectblock", effectAmount:5 },
  { fromId:"hulkbuster", fromStars:3, toId:"superiorironman", effectId:"perfectblock", effectAmount:5 },
  { fromId:"hulkbuster", fromStars:4, toId:"hulk", effectId:"critdamage", effectAmount:25 },
  { fromId:"hulkbuster", fromStars:4, toId:"ironman", effectId:"perfectblock", effectAmount:6 },
  { fromId:"hulkbuster", fromStars:4, toId:"superiorironman", effectId:"perfectblock", effectAmount:6 },

  { fromId:"rocket", fromStars:3, toId:"starlord", effectId:"armor", effectAmount:5 },
  { fromId:"rocket", fromStars:3, toId:"ronan", effectId:"critrate", effectAmount:6 },
  { fromId:"rocket", fromStars:3, toId:"gamora", effectId:"perfectblock", effectAmount:4 },
  { fromId:"rocket", fromStars:3, toId:"drax", effectId:"perfectblock", effectAmount:4 },
  { fromId:"rocket", fromStars:4, toId:"starlord", effectId:"armor", effectAmount:6 },
  { fromId:"rocket", fromStars:4, toId:"ronan", effectId:"critrate", effectAmount:7 },
  { fromId:"rocket", fromStars:4, toId:"gamora", effectId:"perfectblock", effectAmount:5 },
  { fromId:"rocket", fromStars:4, toId:"drax", effectId:"perfectblock", effectAmount:5 },

  { fromId:"starlord", fromStars:2, toId:"rocket", effectId:"armor", effectAmount:4 },
  { fromId:"starlord", fromStars:2, toId:"drax", effectId:"perfectblock", effectAmount:3 },
  { fromId:"starlord", fromStars:3, toId:"rocket", effectId:"armor", effectAmount:5 },
  { fromId:"starlord", fromStars:3, toId:"drax", effectId:"perfectblock", effectAmount:4 },
  { fromId:"starlord", fromStars:3, toId:"gamora", effectId:"perfectblock", effectAmount:4 },
  { fromId:"starlord", fromStars:4, toId:"rocket", effectId:"armor", effectAmount:6 },
  { fromId:"starlord", fromStars:4, toId:"drax", effectId:"perfectblock", effectAmount:5 },
  { fromId:"starlord", fromStars:4, toId:"gamora", effectId:"perfectblock", effectAmount:5 },

  { fromId:"vision", fromStars:2, toId:"scarletwitch", effectId:"powergain", effectAmount:3 },
  { fromId:"vision", fromStars:2, toId:"ironman", effectId:"perfectblock", effectAmount:3 },
  { fromId:"vision", fromStars:3, toId:"scarletwitch", effectId:"powergain", effectAmount:4 },
  { fromId:"vision", fromStars:3, toId:"ironman", effectId:"perfectblock", effectAmount:4 },
  { fromId:"vision", fromStars:4, toId:"scarletwitch", effectId:"powergain", effectAmount:5 },
  { fromId:"vision", fromStars:4, toId:"ironman", effectId:"perfectblock", effectAmount:5 },

  { fromId:"thevision", fromStars:2, toId:"ironman", effectId:"health", effectAmount:4 },
  { fromId:"thevision", fromStars:2, toId:"scarletwitch", effectId:"perfectblock", effectAmount:3 },
  { fromId:"thevision", fromStars:3, toId:"ironman", effectId:"health", effectAmount:5 },
  { fromId:"thevision", fromStars:3, toId:"scarletwitch", effectId:"perfectblock", effectAmount:4 },
  { fromId:"thevision", fromStars:3, toId:"ultron", effectId:"attack", effectAmount:4 },
  { fromId:"thevision", fromStars:4, toId:"ironman", effectId:"health", effectAmount:6 },
  { fromId:"thevision", fromStars:4, toId:"scarletwitch", effectId:"perfectblock", effectAmount:5 },
  { fromId:"thevision", fromStars:4, toId:"ultron", effectId:"attack", effectAmount:5 },

  { fromId:"ultron", fromStars:3, toId:"ironman", effectId:"health", effectAmount:5 },
  { fromId:"ultron", fromStars:3, toId:"scarletwitch", effectId:"armor", effectAmount:5 },
  { fromId:"ultron", fromStars:4, toId:"ironman", effectId:"health", effectAmount:6 },
  { fromId:"ultron", fromStars:4, toId:"scarletwitch", effectId:"armor", effectAmount:6 },
  
  { fromId:"colossus", fromStars:2, toId:"juggernaut", effectId:"critrate", effectAmount:5 },
  { fromId:"colossus", fromStars:3, toId:"juggernaut", effectId:"critrate", effectAmount:6 },
  { fromId:"colossus", fromStars:3, toId:"wolverine", effectId:"armor", effectAmount:5 },
  { fromId:"colossus", fromStars:3, toId:"magik", effectId:"health", effectAmount:4 },
  { fromId:"colossus", fromStars:4, toId:"juggernaut", effectId:"critrate", effectAmount:7 },
  { fromId:"colossus", fromStars:4, toId:"wolverine", effectId:"armor", effectAmount:6 },
  { fromId:"colossus", fromStars:4, toId:"magik", effectId:"health", effectAmount:5 },

  { fromId:"cyclops", fromStars:2, toId:"wolverine", effectId:"critdamage", effectAmount:15 },
  { fromId:"cyclops", fromStars:3, toId:"wolverine", effectId:"critdamage", effectAmount:20 },
  { fromId:"cyclops", fromStars:3, toId:"magneto", effectId:"attack", effectAmount:4 },
  { fromId:"cyclops", fromStars:4, toId:"wolverine", effectId:"critdamage", effectAmount:25 },
  { fromId:"cyclops", fromStars:4, toId:"magneto", effectId:"attack", effectAmount:5 },

  { fromId:"deadpool", fromStars:2, toId:"rhino", effectId:"critrate", effectAmount:5 },
  { fromId:"deadpool", fromStars:2, toId:"wolverine", effectId:"health", effectAmount:3 },
  { fromId:"deadpool", fromStars:2, toId:"punisher", effectId:"perfectblock", effectAmount:3 },
  { fromId:"deadpool", fromStars:3, toId:"rhino", effectId:"critrate", effectAmount:6 },
  { fromId:"deadpool", fromStars:3, toId:"wolverine", effectId:"health", effectAmount:4 },
  { fromId:"deadpool", fromStars:3, toId:"punisher", effectId:"perfectblock", effectAmount:4 },
  { fromId:"deadpool", fromStars:4, toId:"rhino", effectId:"critrate", effectAmount:7 },
  { fromId:"deadpool", fromStars:4, toId:"wolverine", effectId:"health", effectAmount:5 },
  { fromId:"deadpool", fromStars:4, toId:"punisher", effectId:"perfectblock", effectAmount:5 },

  { fromId:"magneto", fromStars:3, toId:"wolverine", effectId:"critrate", effectAmount:6 },
  { fromId:"magneto", fromStars:3, toId:"cyclops", effectId:"block", effectAmount:15 },
  { fromId:"magneto", fromStars:3, toId:"storm", effectId:"critdamage", effectAmount:20 },
  { fromId:"magneto", fromStars:4, toId:"wolverine", effectId:"critrate", effectAmount:7 },
  { fromId:"magneto", fromStars:4, toId:"cyclops", effectId:"block", effectAmount:20 },
  { fromId:"magneto", fromStars:4, toId:"storm", effectId:"critdamage", effectAmount:25 },

  { fromId:"storm", fromStars:2, toId:"blackpanther", effectId:"powergain", effectAmount:3 },
  { fromId:"storm", fromStars:3, toId:"magik", effectId:"armor", effectAmount:6 },
  { fromId:"storm", fromStars:3, toId:"cyclops", effectId:"perfectblock", effectAmount:4 },
  { fromId:"storm", fromStars:3, toId:"blackpanther", effectId:"powergain", effectAmount:4 },
  { fromId:"storm", fromStars:4, toId:"magik", effectId:"armor", effectAmount:7 },
  { fromId:"storm", fromStars:4, toId:"cyclops", effectId:"perfectblock", effectAmount:5 },
  { fromId:"storm", fromStars:4, toId:"blackpanther", effectId:"powergain", effectAmount:5 },
  { fromId:"storm", fromStars:4, toId:"magneto", effectId:"critrate", effectAmount:7 },

  { fromId:"wolverine", fromStars:2, toId:"cyclops", effectId:"critdamage", effectAmount:15 },
  { fromId:"wolverine", fromStars:3, toId:"cyclops", effectId:"critdamage", effectAmount:20 },
  { fromId:"wolverine", fromStars:3, toId:"captainamerica", effectId:"armor", effectAmount:5 },
  { fromId:"wolverine", fromStars:3, toId:"magneto", effectId:"critrate", effectAmount:6 },
  { fromId:"wolverine", fromStars:4, toId:"cyclops", effectId:"critdamage", effectAmount:25 },
  { fromId:"wolverine", fromStars:4, toId:"captainamerica", effectId:"armor", effectAmount:6 },
  { fromId:"wolverine", fromStars:4, toId:"magneto", effectId:"critrate", effectAmount:7 },

  { fromId:"blackpanther", fromStars:2, toId:"ironfist", effectId:"critdamage", effectAmount:15 },
  { fromId:"blackpanther", fromStars:3, toId:"ironfist", effectId:"critdamage", effectAmount:20 },
  { fromId:"blackpanther", fromStars:3, toId:"storm", effectId:"powergain", effectAmount:4 },
  { fromId:"blackpanther", fromStars:3, toId:"deadpool", effectId:"critrate", effectAmount:6 },
  { fromId:"blackpanther", fromStars:4, toId:"ironfist", effectId:"critdamage", effectAmount:25 },
  { fromId:"blackpanther", fromStars:4, toId:"storm", effectId:"powergain", effectAmount:5 },
  { fromId:"blackpanther", fromStars:4, toId:"deadpool", effectId:"critrate", effectAmount:7 },

  { fromId:"daredevil", fromStars:3, toId:"superiorironman", effectId:"critdamage", effectAmount:20 },
  { fromId:"daredevil", fromStars:3, toId:"blackwidow", effectId:"powergain", effectAmount:4 },
  { fromId:"daredevil", fromStars:4, toId:"superiorironman", effectId:"critdamage", effectAmount:25 },
  { fromId:"daredevil", fromStars:4, toId:"blackwidow", effectId:"powergain", effectAmount:5 },

  { fromId:"hawkeye", fromStars:2, toId:"scarletwitch", effectId:"powergain", effectAmount:3 },
  { fromId:"hawkeye", fromStars:3, toId:"scarletwitch", effectId:"powergain", effectAmount:4 },
  { fromId:"hawkeye", fromStars:3, toId:"ironman", effectId:"armor", effectAmount:5 },
  { fromId:"hawkeye", fromStars:4, toId:"scarletwitch", effectId:"powergain", effectAmount:5 },
  { fromId:"hawkeye", fromStars:4, toId:"ironman", effectId:"armor", effectAmount:6 },
  { fromId:"hawkeye", fromStars:4, toId:"hulk", effectId:"armor", effectAmount:6 },

  { fromId:"punisher", fromStars:2, toId:"spiderman", effectId:"critdamage", effectAmount:15 },
  { fromId:"punisher", fromStars:3, toId:"spiderman", effectId:"critdamage", effectAmount:20 },
  { fromId:"punisher", fromStars:3, toId:"rhino", effectId:"perfectblock", effectAmount:4 },
  { fromId:"punisher", fromStars:4, toId:"spiderman", effectId:"critdamage", effectAmount:25 },
  { fromId:"punisher", fromStars:4, toId:"rhino", effectId:"perfectblock", effectAmount:5 },

  { fromId:"wintersoldier", fromStars:2, toId:"wolverine", effectId:"armor", effectAmount:4 },
  { fromId:"wintersoldier", fromStars:2, toId:"captainamerica", effectId:"perfectblock", effectAmount:3 },
  { fromId:"wintersoldier", fromStars:3, toId:"wolverine", effectId:"armor", effectAmount:5 },
  { fromId:"wintersoldier", fromStars:3, toId:"captainamerica", effectId:"perfectblock", effectAmount:4 },
  { fromId:"wintersoldier", fromStars:4, toId:"wolverine", effectId:"armor", effectAmount:6 },
  { fromId:"wintersoldier", fromStars:4, toId:"captainamerica", effectId:"perfectblock", effectAmount:5 },

  { fromId:"blackwidow", fromStars:2, toId:"msmarvel", effectId:"armor", effectAmount:4 },
  { fromId:"blackwidow", fromStars:2, toId:"wintersoldier", effectId:"powergain", effectAmount:3 },
  { fromId:"blackwidow", fromStars:3, toId:"hulk", effectId:"stun", effectAmount:20 },
  { fromId:"blackwidow", fromStars:3, toId:"msmarvel", effectId:"armor", effectAmount:5 },
  { fromId:"blackwidow", fromStars:3, toId:"wintersoldier", effectId:"powergain", effectAmount:4 },
  { fromId:"blackwidow", fromStars:3, toId:"hawkeye", effectId:"powergain", effectAmount:4 },
  { fromId:"blackwidow", fromStars:4, toId:"hulk", effectId:"stun", effectAmount:25 },
  { fromId:"blackwidow", fromStars:4, toId:"msmarvel", effectId:"armor", effectAmount:6 },
  { fromId:"blackwidow", fromStars:4, toId:"wintersoldier", effectId:"powergain", effectAmount:5 },
  { fromId:"blackwidow", fromStars:4, toId:"hawkeye", effectId:"powergain", effectAmount:5 },

  { fromId:"abomination", fromStars:2, toId:"rhino", effectId:"armor", effectAmount:4 },
  { fromId:"abomination", fromStars:3, toId:"rhino", effectId:"armor", effectAmount:5 },
  { fromId:"abomination", fromStars:3, toId:"hulk", effectId:"attack", effectAmount:4 },
  { fromId:"abomination", fromStars:4, toId:"rhino", effectId:"armor", effectAmount:6 },
  { fromId:"abomination", fromStars:4, toId:"hulk", effectId:"attack", effectAmount:5 },

  { fromId:"captainamerica", fromStars:2, toId:"spiderman", effectId:"armor", effectAmount:4 },
  { fromId:"captainamerica", fromStars:2, toId:"superiorironman", effectId:"critrate", effectAmount:5 },
  { fromId:"captainamerica", fromStars:2, toId:"ironman", effectId:"armor", effectAmount:3 },
  { fromId:"captainamerica", fromStars:3, toId:"wintersoldier", effectId:"armor", effectAmount:5 },
  { fromId:"captainamerica", fromStars:3, toId:"spiderman", effectId:"armor", effectAmount:5 },
  { fromId:"captainamerica", fromStars:3, toId:"superiorironman", effectId:"critrate", effectAmount:6 },
  { fromId:"captainamerica", fromStars:3, toId:"ironman", effectId:"perfectblock", effectAmount:4 },
  { fromId:"captainamerica", fromStars:4, toId:"wintersoldier", effectId:"armor", effectAmount:6 },
  { fromId:"captainamerica", fromStars:4, toId:"spiderman", effectId:"armor", effectAmount:6 },
  { fromId:"captainamerica", fromStars:4, toId:"superiorironman", effectId:"critrate", effectAmount:7 },
  { fromId:"captainamerica", fromStars:4, toId:"ironman", effectId:"perfectblock", effectAmount:5 },

  { fromId:"electro", fromStars:3, toId:"spiderman", effectId:"attack", effectAmount:4 },
  { fromId:"electro", fromStars:3, toId:"rhino", effectId:"armor", effectAmount:5 },
  { fromId:"electro", fromStars:4, toId:"spiderman", effectId:"attack", effectAmount:5 },
  { fromId:"electro", fromStars:4, toId:"rhino", effectId:"armor", effectAmount:6 },

  { fromId:"hulk", fromStars:2, toId:"thor", effectId:"critdamage", effectAmount:15 },
  { fromId:"hulk", fromStars:3, toId:"thor", effectId:"armor", effectAmount:5 },
  { fromId:"hulk", fromStars:3, toId:"abomination", effectId:"critrate", effectAmount:6 },
  { fromId:"hulk", fromStars:3, toId:"hawkeye", effectId:"critdamage", effectAmount:20 },
  { fromId:"hulk", fromStars:4, toId:"thor", effectId:"armor", effectAmount:6 },
  { fromId:"hulk", fromStars:4, toId:"abomination", effectId:"critrate", effectAmount:7 },
  { fromId:"hulk", fromStars:4, toId:"hawkeye", effectId:"critdamage", effectAmount:25 },

  { fromId:"rhino", fromStars:2, toId:"spiderman", effectId:"critrate", effectAmount:5 },
  { fromId:"rhino", fromStars:2, toId:"abomination", effectId:"armor", effectAmount:4 },
  { fromId:"rhino", fromStars:3, toId:"spiderman", effectId:"critrate", effectAmount:6 },
  { fromId:"rhino", fromStars:3, toId:"abomination", effectId:"armor", effectAmount:5 },
  { fromId:"rhino", fromStars:3, toId:"electro", effectId:"perfectblock", effectAmount:4 },
  { fromId:"rhino", fromStars:4, toId:"spiderman", effectId:"critrate", effectAmount:7 },
  { fromId:"rhino", fromStars:4, toId:"abomination", effectId:"armor", effectAmount:6 },
  { fromId:"rhino", fromStars:4, toId:"electro", effectId:"perfectblock", effectAmount:5 },

  { fromId:"spiderman", fromStars:1, toId:"wolverine", effectId:"health", effectAmount:5 },
  { fromId:"spiderman", fromStars:1, toId:"hawkeye", effectId:"attack", effectAmount:5 },
  { fromId:"spiderman", fromStars:2, toId:"wolverine", effectId:"health", effectAmount:5 },
  { fromId:"spiderman", fromStars:2, toId:"hawkeye", effectId:"attack", effectAmount:5 },
  { fromId:"spiderman", fromStars:3, toId:"wolverine", effectId:"health", effectAmount:5 },
  { fromId:"spiderman", fromStars:3, toId:"hawkeye", effectId:"attack", effectAmount:5 },
  { fromId:"spiderman", fromStars:3, toId:"electro", effectId:"health", effectAmount:6 },
  { fromId:"spiderman", fromStars:3, toId:"captainamerica", effectId:"attack", effectAmount:5 },
  { fromId:"spiderman", fromStars:4, toId:"wolverine", effectId:"health", effectAmount:6 },
  { fromId:"spiderman", fromStars:4, toId:"hawkeye", effectId:"attack", effectAmount:6 },
  { fromId:"spiderman", fromStars:4, toId:"electro", effectId:"health", effectAmount:7 },
  { fromId:"spiderman", fromStars:4, toId:"captainamerica", effectId:"attack", effectAmount:6 },

  { fromId:"drstrange", fromStars:3, toId:"thor", effectId:"armor", effectAmount:5 },
  { fromId:"drstrange", fromStars:3, toId:"spiderman", effectId:"armor", effectAmount:5 },
  { fromId:"drstrange", fromStars:3, toId:"scarletwitch", effectId:"block", effectAmount:15 },
  { fromId:"drstrange", fromStars:3, toId:"blackbolt", effectId:"perfectblock", effectAmount:4 },
  { fromId:"drstrange", fromStars:4, toId:"thor", effectId:"armor", effectAmount:6 },
  { fromId:"drstrange", fromStars:4, toId:"spiderman", effectId:"armor", effectAmount:6 },
  { fromId:"drstrange", fromStars:4, toId:"scarletwitch", effectId:"block", effectAmount:20 },
  { fromId:"drstrange", fromStars:4, toId:"blackbolt", effectId:"perfectblock", effectAmount:5 },

  { fromId:"ironfist", fromStars:2, toId:"blackpanther", effectId:"armor", effectAmount:4 },
  { fromId:"ironfist", fromStars:3, toId:"blackpanther", effectId:"armor", effectAmount:5 },
  { fromId:"ironfist", fromStars:3, toId:"drstrange", effectId:"armor", effectAmount:5 },

  { fromId:"juggernaut", fromStars:2, toId:"colossus", effectId:"critrate", effectAmount:5 },
  { fromId:"juggernaut", fromStars:3, toId:"drstrange", effectId:"attack", effectAmount:4 },
  { fromId:"juggernaut", fromStars:3, toId:"colossus", effectId:"critrate", effectAmount:6 },
  { fromId:"juggernaut", fromStars:3, toId:"hulk", effectId:"critrate", effectAmount:6 },
  { fromId:"juggernaut", fromStars:4, toId:"drstrange", effectId:"attack", effectAmount:5 },
  { fromId:"juggernaut", fromStars:4, toId:"colossus", effectId:"critrate", effectAmount:7 },
  { fromId:"juggernaut", fromStars:4, toId:"hulk", effectId:"critrate", effectAmount:7 },

  { fromId:"magik", fromStars:2, toId:"colossus", effectId:"health", effectAmount:4 },
  { fromId:"magik", fromStars:3, toId:"storm", effectId:"armor", effectAmount:5 },
  { fromId:"magik", fromStars:3, toId:"colossus", effectId:"health", effectAmount:5 },
  { fromId:"magik", fromStars:3, toId:"cyclops", effectId:"perfectblock", effectAmount:4 },
  { fromId:"magik", fromStars:4, toId:"storm", effectId:"armor", effectAmount:6 },
  { fromId:"magik", fromStars:4, toId:"colossus", effectId:"health", effectAmount:6 },
  { fromId:"magik", fromStars:4, toId:"cyclops", effectId:"perfectblock", effectAmount:5 },
  { fromId:"magik", fromStars:4, toId:"juggernaut", effectId:"critrate", effectAmount:7 },

  { fromId:"scarletwitch", fromStars:2, toId:"captainmarvel", effectId:"armor", effectAmount:4 },
  { fromId:"scarletwitch", fromStars:3, toId:"captainmarvel", effectId:"armor", effectAmount:5 },
  { fromId:"scarletwitch", fromStars:3, toId:"vision", effectId:"powergain", effectAmount:4 },

  { fromId:"unstoppablecolossus", fromStars:2, toId:"magik", effectId:"health", effectAmount:4 },
  { fromId:"unstoppablecolossus", fromStars:2, toId:"juggernaut", effectId:"critdamage", effectAmount:15 },
  { fromId:"unstoppablecolossus", fromStars:3, toId:"wolverine", effectId:"armor", effectAmount:5 },
  { fromId:"unstoppablecolossus", fromStars:3, toId:"magik", effectId:"health", effectAmount:5 },
  { fromId:"unstoppablecolossus", fromStars:3, toId:"cyclops", effectId:"perfectblock", effectAmount:4 },
  { fromId:"unstoppablecolossus", fromStars:3, toId:"juggernaut", effectId:"critdamage", effectAmount:20 },
  { fromId:"unstoppablecolossus", fromStars:4, toId:"wolverine", effectId:"armor", effectAmount:6 },
  { fromId:"unstoppablecolossus", fromStars:4, toId:"magik", effectId:"health", effectAmount:6 },
  { fromId:"unstoppablecolossus", fromStars:4, toId:"cyclops", effectId:"perfectblock", effectAmount:5 },
  { fromId:"unstoppablecolossus", fromStars:4, toId:"juggernaut", effectId:"critdamage", effectAmount:25 }
  
], {
  model: CoC.model.Synergy
});